Adopt clean architecture
the-sortinghat/ProtoINCT pull request #3
Opened 2021-06-11 14:00 UTC by jooaodanieel

2021-06-11 19:18 UTC, erickrodrigs requested changes
@jooaodanieel gostei da nova estrutura, acho que seria uma boa a gente pode adotar. Porém, gostaria de fazer alguns comentários, tanto sobre essa nova estrutura quanto sobre a implementação de grafos:

- Sobre os visitors, qual seria o melhor lugar para colocá-los? vi que você colocou dentro de `entities`, porém eu vejo eles como um "algo diferente", sabe? não sei se exatamente um UseCase, porque não são ações da nossa aplicação. Eles seriam utilizados pelo RegisterSystem UseCase. Acho que o melhor seria colocá-los dentro de uma pasta `visitors`, da mesma forma que você criou as interfaces.
-  Achei alguns errors na implementação dos grafos: veja que no arquivo `entities/system.ts` você está tentando usar uma classe `Node` que não existe mais. No método `accept(v: Visitor): void` você também tenta acessar um atributo `node` da classe `Edge` que também não existe. Acredito que foi um erro que passou despercebido, já que você não importou a classe `System` em nenhum outro lugar (Não consegui mostrar via código aqui nesse PR pois isso foi uma modificação que você fez direto na branch `collector`, aí não entrou como modificação desse PR).

2021-06-11 19:28 UTC, erickrodrigs commented on collector/src/framework/controllers/repositories_controller.ts
> +    const savedSystem = await RegisterSystem.run(repoURL, dependencies);
Será que aqui a gente não conseguiria aproveitar mais do Typescript para fazer a injeção de dependência? Digo, você criou e passou um objeto simples pro `RegisterSystem.run`, e lá dentro você fez uma desestruturação simples, esperando algo com type `any`. Será que não valeria a pena criar uma interface nesse caso? Não sei se estou sendo muito preciosista, já que provavelmente vamos usar somente nesse caso, mas essa implementação atual tem muito uma cara de javascript normal, saca?

2021-06-11 20:51 UTC, jooaodanieel commented
salve @erickrodrigs 

> * Sobre os visitors, qual seria o melhor lugar para colocá-los? vi que você colocou dentro de `entities`, porém eu vejo eles como um "algo diferente", sabe? não sei se exatamente um UseCase, porque não são ações da nossa aplicação. Eles seriam utilizados pelo RegisterSystem UseCase. Acho que o melhor seria colocá-los dentro de uma pasta `visitors`, da mesma forma que você criou as interfaces.

Os visitors não são usecases, porque eles são entidades do nosso core. Podemos criar mais pastas dentro do `./src/core/entities`, tipo `graph`, `visitors` etc, caso você ache que isso melhora. Um caso de uso seria uma articulação de alguma coisa, mas eu acho que um visitor ainda é uma entidade do core.

-----

> * Achei alguns errors na implementação dos grafos: veja que no arquivo `entities/system.ts` você está tentando usar uma classe `Node` que não existe mais. No método `accept(v: Visitor): void` você também tenta acessar um atributo `node` da classe `Edge` que também não existe. Acredito que foi um erro que passou despercebido, já que você não importou a classe `System` em nenhum outro lugar (Não consegui mostrar via código aqui nesse PR pois isso foi uma modificação que você fez direto na branch `collector`, aí não entrou como modificação desse PR).

De fato faltou apagar alguns arquivos nos commits que foram direto na `collector`. Depois arrumamos, sem problema.

2021-06-11 20:52 UTC, jooaodanieel commented on collector/src/framework/controllers/repositories_controller.ts
> +    const savedSystem = await RegisterSystem.run(repoURL, dependencies);
Sem dúvidas! Na real, eu apenas comecei uma estruturação com clean architecture, mas não está do jeito que eu gostaria. Outro exemplo bem concreto é o `http: axios`. Fiz isso para, em breve, encapsular o axios em um objeto controlado nosso que seja responsável pelas requisições http.

2021-06-11 22:32 UTC, brunopromano approved these changes

2021-06-13 18:04 UTC, jooaodanieel commented
@erickrodrigs coloquei mais um commit aqui. Ele apenas remove as classes que não seriam utilizadas.
Os demais ajustes que você mencionou podemos fazer com o tempo, via refatorações pontuais "injetadas" nos próximos PRs.
O que acha?

2021-06-13 18:22 UTC, erickrodrigs approved these changes

2021-06-13 18:24 UTC, merged